### ISSUE TITLE
User's Profile content

### ISSUE THREAD

**Issue by tyladevon** [TreatYoSelf/react_fe#7]
**Describe the functionality or user interaction with the app**
As a User, when I visit my 'profile' page, I see a section to set or update my suggested 'Treats' or 'Activities'
**Describe associated tests**
Test user can see section and content of section
**Related Issues**
#9 

**Tasks**
Create Structure
- [ ] Set up landing component structure
- [ ] Incorporate treat map
- [ ] add styling
- [ ] create snapshot testing
- [ ] create Pack?
