### ISSUE TITLE
User's Calendar 

### ISSUE THREAD

**Issue by tyladevon** [TreatYoSelf/react_fe#8]
**Describe the functionality or user interaction with the app**
As a User, when I visit my 'profile' page, I see my calendar where I can update my schedule.
**Describe associated tests**
Test calendar is rendered on profile page. Test user can update it.
**Related Issues**

**Tasks**
Create Structure
- [ ] Set up landing component structure
- [ ] Incorporate treat map
- [ ] add styling
- [ ] create snapshot testing
- [ ] create Pack?

<img width="321" alt="Screen Shot 2020-04-04 at 7 18 20 PM" src="https://user-images.githubusercontent.com/39674585/78464646-0e519680-76a9-11ea-9dcc-5853f6f9a86e.png">
