### ISSUE TITLE
User's Treat

### ISSUE THREAD

**Issue by joel-oe-lacey** [TreatYoSelf/react_fe#9]
**Describe the functionality or user interaction with the app**
As a User, when viewing a treat on my profile, it should include an icon, the task name, and a rating drop down. If viewed on my schedule it should include an icon, the task name, and the task duration.

**Describe associated tests**
Treat is rendered within profile and can be interacted with to post rating.

**Related Issues**

**Tasks**
Create Structure
- [ ] Set up landing component structure
- [ ] add styling
- [ ] include combobox 
- [ ] create snapshot testing
- [ ] create interaction testing

Conditional Alternative
- [ ] Set up landing component structure
- [ ] add styling
- [ ] create snapshot testing for different param

<img width="310" alt="Screen Shot 2020-04-04 at 7 19 55 PM" src="https://user-images.githubusercontent.com/39674585/78464660-4658d980-76a9-11ea-80cc-2dbafae0c0fd.png">
